### ISSUE TITLE
Cron is not running as scheduled

### ISSUE THREAD

**Issue by christianto88** [Hexagon/croner#156]
```
const cron = Cron({"*/2 * * * *", async () => {
     console.log("Cron is running");
     // some long running tasks that takes more than 2 minute
     await fetchDataFromAPI();
     await processData();
    });
```

I have this code which is supposed to invoked the function every to 2 minutes. But since the function takes more than 2 minute to complete, the functions is not invoked in the next 2 minutes. 
Is this the intended behavior? Isn't that cron is expected to execute for every 2 minutes interval?

**Comment by Hexagon** [comment]
Hi!

Thanks for reporting!

Until very recently, if you passed an async function, croner just fire-and-forgetted it.

From `5.4.1` a feature were added to specify a custom error handler (callback). To make this work i had to await the supplied function (to be able to catch any errors). By mistake await is also run when no custom error handler is passed - so it is a bug. Will have a look at that! 

Meanwhile, you can use version `5.3.5` which do not have this behavior.

**Comment by Hexagon** [comment]
Fixed in `5.4.2`

**Comment by MZPL** [comment]
Looks like this issue will still appear when `catch` is defined, as it's still awaiting the promise.
```js
import cron from "croner";

async function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

cron("*/5 * * * * *", async () => {
  console.log("Start", new Date().toISOString());
  await sleep(10_000);
  console.log("End", new Date().toISOString());
})

/*
Output (ok):
Start 2023-02-01T22:49:05.004Z
Start 2023-02-01T22:49:10.004Z
Start 2023-02-01T22:49:15.003Z
End 2023-02-01T22:49:15.044Z
Start 2023-02-01T22:49:20.004Z
End 2023-02-01T22:49:20.006Z
...


The same code, but `catch` is defined (not ok):
Start 2023-02-01T22:53:15.003Z
End 2023-02-01T22:53:25.030Z
Start 2023-02-01T22:53:30.004Z
End 2023-02-01T22:53:40.014Z
*/
```
Perhaps this could be fixed by using `.catch(() => try..catch code here)` without `await`  instead?

**Comment by Hexagon** [comment]
Oh, will have a look at this, if you're not up to it? :)

**Comment by Hexagon** [comment]
I'll look into this now

**Comment by Hexagon** [comment]
Fixed in `5.5.1`
